### ISSUE TITLE
Transition the Flask API from api-test.openfisca.fr to fr.openfisca.org/api/v18

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-ops#12]
Considering [how low](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=range&date=last30#?module=Actions&action=menuGetPageUrls&idSite=4&period=range&date=last30&popover=RowAction$3ARowEvolution$3AActions.getPageUrls$3A$257B$257D$3Aapi) the traffic is to the current version of `api.openfisca.fr`, we can safely consider that no production tool depends on it.

On the other hand, `api-test.openfisca.fr` has [considerable traffic](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=range&date=last30#?module=Actions&action=menuGetPageUrls&idSite=4&period=range&date=last30&popover=RowAction$3ARowEvolution$3AActions.getPageUrls$3A$257B$257D$3A$40$252Fparameters), has proven its stability, and is getting more feature-complete.

We will thus progressively transition `api.openfisca.fr` to host the Flask API.

The proposed steps are as follow:

## 2017-09-01

- Migrate all endpoints from the current `api-test.openfisca.fr/` to `api.openfisca.fr/2/` with a `302 Temporary Redirect`.
- Upon validation that the new host works properly, update the documentation and legislation explorer to explicitly mention this new host.

### Breaking changes

- Reusers that have not set up their API to follow redirects will have to manually update their target host.

## 2017-09-08

_Considering there were no issues. If issues arise, wait 7 days after the last incident._

- Announce the change to the community, publishing this roadmap.
- Update the documentation to show that the “official” API is now the one at `api.openfisca.fr/2`. Deprecate the previous documentation, but still keep it in the official documentation.
- Switch the `api-test.openfisca.fr/` to `api.openfisca.fr/2/` redirection to a `301 Permanent Redirect`.
- Add a `"deprecationNotice"` property to all JSON replies in the legacy API explaining the switch and giving a link to this roadmap.
- Deprecate the `web-api` package, directing users to the documentation and this roadmap.

_From this moment on, the change is irreversible. If issues arise, they will be handled as production incidents, but the Flask API will be considered as the official one._

### Breaking changes

None.

## 2017-10-01

_Assuming that there are still users of the legacy API, as proven by the [stats](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=range&date=last30#?module=Actions&action=menuGetPageUrls&idSite=4&period=range&date=last30&popover=RowAction$3ARowEvolution$3AActions.getPageUrls$3A$257B$257D$3Aapi)._

- Every 1 requests out of 50 (approximately), replace a response from the legacy API with a [`510 Not Extended` response](https://tools.ietf.org/html/rfc2774#section-7) whose body explicitly states that this API is being replaced and that clients should move to the new one or host their own version, providing links to this roadmap and to the documentation, and explaining that the request simply has to be retried.

### Breaking changes

- Users of `api.openfisca.fr` will receive intermittent errors until they upgrade to the new version of the API.

## 2017-11-01

- The web-api package and its deployment to `api.openfisca.fr` will simply not be maintained anymore. Once a change in Core breaks compatibility and deployment to `api.openfisca.fr` fails, deactivate hooks to deploy the web-api to `api.openfisca.fr`.

- - - -

poke @cbenz @benjello @fpagnoux @Morendil @xtrembaker

**Comment by fpagnoux** [comment]
As a result of the workshop mentioned in https://github.com/openfisca/openfisca-core/issues/570, it has been decided that `api-test.openfisca.fr` will be redirected to `fr.openfisca.org/api/v18`, `18` being the major version of france right now. I am therefore renaming the issue.

**Comment by fpagnoux** [comment]
About the maintenance of the legacy `web-api` package, I'd wait that at least mes-aides.gouv.fr has migrated to the new API before stopping maintaining it.

**Comment by fpagnoux** [comment]
I think the transition is now over. The old API is not maintained anymore.
