### ISSUE TITLE
Ansible configuration for web APIs services uses a Python version behind OpenFisca reference version

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-ops#125]
The [ansible configuration installs Python 3.7 for the web API services](https://github.com/openfisca/openfisca-ops/blob/dca9cb07a8d2cfe5532c05e3aed699425d9b8b0b/ansible/roles/openfisca_api/tasks/main.yml#L22) (demo and France) while `openfisca-core` [now needs Python 3.9+](https://github.com/openfisca/openfisca-core/blob/2c04dae03206655826ee529c083d0876061b6655/setup.py#L76).

**Should we update to Python 3.9 or a newer revision?**
`openfisca-core` library is [compatible with Python 3.9, 3.10 and 3.11](https://github.com/openfisca/openfisca-core/blob/2c04dae03206655826ee529c083d0876061b6655/setup.py#L76). So we have multiple options: 
1️⃣ Use Python 3.9 on our server to check if the web API is still working as expected for users with older systems.
2️⃣ Use Python [3.10.6 as it's the current Python version used to test the library in the CI](https://github.com/openfisca/openfisca-core/blob/2c04dae03206655826ee529c083d0876061b6655/.github/workflows/workflow.yml#L53) (the CI can use multiple versions so, we can choose to set our server default Python revision to the latest Python used in the CI).
3️⃣ Use Python 3.11 on our server to check that the web API works as expected in production with the latest Python version supported by `openfisca-core`.

**Can we keep Python 3.7 for some time on our server?**
No. `openfisca-core` now needs [numpy >=1.24.2, <1.25](https://github.com/openfisca/openfisca-core/blob/2c04dae03206655826ee529c083d0876061b6655/setup.py#L33C12-L33C27) and [numpy 1.24 documentation](https://numpy.org/doc/stable/release/1.24.0-notes.html) says: "This release supports Python versions 3.8-3.11.". So, using the web API with Python 3.7 might raise some issues with the `/calculate` endpoint.

**So, we move to Python 3.9/3.10 or 3.11 in ansible configuration and that's it?**
We detected performance issues when we updated the Python version to 3.9+. Some fixes have been merged like https://github.com/openfisca/openfisca-core/pull/1188 and https://github.com/openfisca/openfisca-core/pull/1189 but we might need to check the response time of the demo/fr web API on the server.

**Comment by MattiSG** [comment]
Thanks @sandcha for this clear recap!

I am clearly in favour of 3️⃣ and upgrading to the latest supported version of Python, in order to minimise maintenance on the infrastructure for later upgrades.

**Comment by MattiSG** [comment]
Fixed by https://github.com/openfisca/openfisca-ops/pull/126.
