### ISSUE TITLE
Auto-renew certificates

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-ops#14]
The SSL certificates of the various `*.openfisca.fr` subdomains often expire. They need to be automatically renewed with CertBot so that the websites are still available without a manuel intervention every trimester.

**Comment by fpagnoux** [comment]
Good news : Uptime Robot will soon warn us in case of a soon expiring certificate.

Still, auto-renewal would be one less thing to worry about.

**Comment by Morendil** [comment]
Are we still renewing manually now?

**Comment by Morendil** [comment]
(Poke @maukoquiroga @sandcha)

**Comment by maukoquiroga** [comment]
@Morendil No, auto renewal is setup, but not working.
