### ISSUE TITLE
Infinite loop in upgrading packages

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-ops#2]
Given those venv contents:

```
OpenFisca-Core                     4.3.3
OpenFisca-France                   13.1.1      
OpenFisca-Web-API                  3.1.0       
```

and those constraints for `OpenFisca-Web-API`:

```
    extras_require = {
        'paster': [
            'PasteScript',
            ],
        'france': [
            'OpenFisca-France >= 5.0.0, < 7.0',
            ],
        'test': [
            'nose',
            ],
        },
    install_requires = [
        'Babel >= 0.9.4',
        'Biryani[datetimeconv] >= 0.10.4',
        'numpy >= 1.11',
        'OpenFisca-Core >= 4.2.2, < 5.0',
        'OpenFisca-Parsers >= 1.0.0, < 2.0',
        'PasteDeploy',
        'WebError >= 0.10',
        'WebOb >= 1.1',
        ],
```

and having `OpenFisca-Core` 5.0.0 published,

executing the [`update-openfisca-virtualenv.sh`](https://github.com/openfisca/openfisca-ops/blob/master/auto-update-pip-packages/update-openfisca-virtualenv.sh) every 5 minutes via cron causes an infinite loop.

More precisely, the script leaves the venv in the same state than before.

It's [designed](https://github.com/openfisca/openfisca-ops/blob/master/auto-update-pip-packages/update-openfisca-virtualenv.sh#L5) to upgrade packages in a specific order: `OpenFisca-France OpenFisca-Core OpenFisca-Web-API`.
Given this order, `OpenFisca-Core` is updated to 5.0.0, then downgraded to 4.3.3.

If we change the order to `OpenFisca-Web-API OpenFisca-France OpenFisca-Core`, `OpenFisca-Core` is upgraded to 5.0.0 **even if this breaks `OpenFisca-Web-API` constraints**!

We have to find a solution:
- a workaround would be to reconstitute `OpenFisca-Web-API` requirements with
    ```
    python -c "import pkg_resources; print(' '.join(map(lambda x: repr(str(x)), pkg_resources.get_distribution('OpenFisca-Web-API').requires())))"
    ```
    and reuse this list in the [pip install](https://github.com/openfisca/openfisca-ops/blob/3476c1f28c1f8fa470321ea0ba891311431184fe/auto-update-pip-packages/update-openfisca-virtualenv.sh#L16) command of the script.
- or we could re-create the venv from scratch, but remember that the cron runs every 5 minutes. We could adopt a push model instead of polling.

CC @l-vincent-l

**Comment by cbenz** [comment]
The `extras_require / france` has been removed. I think that this makes this issue irrelevant.

Let's test on several updates and if the problem has really disappeared, I'll close it.

**Comment by fpagnoux** [comment]
Probably fixed by https://github.com/openfisca/openfisca-web-api/pull/92

**Comment by MattiSG** [comment]
Reappears.

**Comment by MattiSG** [comment]
I'll open another issue to be more specific.
