### ISSUE TITLE
Deploy continuously on api.openfisca.fr

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-ops#4]
- `api.openfisca.fr` MUST always be up-to-date of the latest `openfisca-france`.
- It SHOULD use the most recent `openfisca-web-api` that supports the above constraint.

This is probably to be done through a deploy hook in the `france` and `web-api` CIs, which would ping a deploy script on the production machine that solves version constraints. This implementation would also scale more easily to other country packages.

Example hooks and scripts should be provided in `ops`.

This worked at some point, but the architecture failed at constraint solving, leading to #2.

**Comment by MattiSG** [comment]
The constraint solver has to be tested:

- Check that incompatible `core` versions of `api` and `france` do not trigger an update.
- Check that compatible `core` versions of `api` and `france` do trigger an update.

**Comment by MattiSG** [comment]
- [ ] Install `api` as an optional dependency of `france`.
- [ ] Add it to the boilerplate.
- [ ] Document in `ops` that this is a condition for country implementers to deploy continuously.

**Comment by fpagnoux** [comment]
> Install api as an optional dependency of france (rather than solving constraints manually).

We experimented with @cbenz, and it appears that pip _never_ resolves transitives dependencies, no matter if they are in a `requirements.txt` files, in extra requires, or even in regular install requires.

So either we give up continuous deployment (and we manually update a `requirements.txt` file in `openfisca-ops`, or we resolve dependencies manually (potentially trough a lib).

**Comment by fpagnoux** [comment]
### Decision :

- A change on Web-Api that adapts it to a new major version of Core must be a breaking change, so that it doesn't install a core version incompatible with the loaded country package.

**Comment by fpagnoux** [comment]
- [ ]  Add it to the CONTRIBUTING

**Comment by fpagnoux** [comment]
The issue should be fixed, however, it seems wise to wait at least for one upgrade of `france` and `api` to make sure everything is working before closing the issue.

- After one upgrade of `france`:
  - [ ] The legacy API is updated
  - [ ] The "new" API is updated
  - [ ] The legislation explorer is updated


- After one upgrade of `web-api`:
  - [ ] The legacy API is updated
  - [ ] The legislation explorer is updated

**Comment by fpagnoux** [comment]
Observation : 

Following a major upgrade of `france`, the API has **not** been upgraded. This is the expected behaviour. However, we are now stuck at 17.2.0.

**Comment by fpagnoux** [comment]
To enable flask api deployment, I upgraded to version 18. 
https://github.com/openfisca/openfisca-france/pull/739/files should be an example of a france update triggering a deployment.

**Comment by fpagnoux** [comment]
Le merge de la nouvelle version de l'API a provoqué une chute du serveur https://api-test.openfisca.fr/ :(

**Comment by fpagnoux** [comment]
I think we cannot reasonably keep investing on this issue if we don't simplify the versionning by merging the 2 apis and the parsers into the core.

**Comment by MattiSG** [comment]
Indeed, we'll merge the flask API into the core through https://github.com/openfisca/openfisca-web-api/issues/129.

**Comment by fpagnoux** [comment]
## 
Half-successful test : a `france` evolution that was not a major bump triggered a successful upgrade of both the legacy and preview APIs.
However, the legislation explorer didn't upgrade its version.

**Comment by MattiSG** [comment]
Two months with no known major problems. We'll reopen other issues if new problems arise.
