### ISSUE TITLE
Add a /latest route to the API

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/openfisca-ops#54]
I propose we create a "/latest" route that will always host the laters version of the openfisca-france api.
the url would be `fr.openfisca.org/api/latest`

---

@maukoquiroga To discuss and to find the good strategy for version management.

Definition of done:

- [x] /latest exists and is automatically deployed when France (and Core ?) is updated #75 
- [x] The doc indicates our public API versionning policy openfisca/openfisca-doc#179

**Comment by fpagnoux** [comment]
I agree that we need this route to maintain an up-to-date version of the legislation explorer. 

About the versioning strategy, I'd suggest the following.
- The OpenFisca Core team always serves the latest version of France under `fr.openfisca.org/api/latest` or `fr.openfisca.org/api/edge`
    - This API has **no** guarantee of stability over time. Building a Web APP on top of that is **not recommended**.
- The OpenFisca Core team always serve two stable versions of the Web API. Every 6 months, on January 1st and July 1st, the oldest stable API is shut down, and the current newest version of France is serve instead. Practically, this means every API version is maintained for a year.
    - These stable APIs are meant to be used by users trying to build web app POCs, and don't want to deal with overnight breaking changes. However, they relatively quickly become outdated.

Any users wanting _both_ freshness and stability are invited to host their own instance of the Web API.

**Comment by fpagnoux** [comment]
Alternative policies:
- Same as above, but only serve a new API once a year.
    - Twice less work !
    - More stability, less freshness
- Not serve any stable API at all.
    -Seems more risky to me, as we definitely had issues in the past with POCs builders being angry about overnight breaking changes.

**Comment by maukoquiroga** [comment]
I like the first one you proposed.

**Comment by alexsegura** [comment]
There is a Terms of service link [here](https://fr.openfisca.org/legislation/swagger), but it lands on a page about publishing recommendations.

**Comment by fpagnoux** [comment]
Yep, that's more the "terms of service" to respect the license.

**Comment by fpagnoux** [comment]
Definition of done:
- `/latest` exists and is automatically deployed
- The doc indicates our public API versionning policy

**Comment by maukoquiroga** [comment]
Hey @fpagnoux, I can't just remember what should we add to the versioning policy :

- How do we shut them down, or
- How do we version the API ?

**Comment by fpagnoux** [comment]
Mostly the content of [this comment](https://github.com/openfisca/openfisca-ops/issues/54#issuecomment-438911658), i.e. clarify that users have the choice between:

- Using an old stable API
- Using a fresh unstable API
- Hosting their own instance
