### ISSUE TITLE
Use Python 3 on the server

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-ops#66]
OpenFisca will stop Python 2 compatibility on January 1st.
Yet, we still use Python 2 in our own server!

Time to upgrade :)

**Comment by maukoquiroga** [comment]
Hey @fpagnoux, I'm guessing this issue has already been shipped?

**Comment by fpagnoux** [comment]
Nope, I broke the server and the only thing I did was putting it back together 😄.

**Comment by fpagnoux** [comment]
All OpenFisca APIs now run on Python 3.5.3 (latest version available with Debian 9)

**Comment by fpagnoux** [comment]
Finally got everything to run on Python 3.7, using [pyenv](https://github.com/pyenv/pyenv-installer).

This was far from obvious, and I ran into many frustrating bugs during previous trials. This makes me wonder if we were not a little too ambitious by stating that 3.7 was the minimal Python version 😞 

I wonder if maintaining support for Python 3.5, or at least 3.6,  would not be a smarter choice, as otherwise users may suffer while trying to install 3.7...
