### ISSUE TITLE
Script 100% server intervention (avoid human)

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-ops#67]
Based on service interruption described here:

- https://twitter.com/OpenFisca/status/1047638855833280513
- https://docs.google.com/document/d/1kHeKzGDR-tj3W4ZXFlYnujDcQDehPyzU4rjH1VORDlg/edit?usp=sharing

I propose we script server provisioning and config (deployment is already scripted) not so much to avoid yesterday's incident but more to be able to rebuild one from scratch at any moment.

**Comment by Morendil** [comment]
Closing as stale.
