### ISSUE TITLE
Update wiki.openfisca.fr state

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-ops#69]
Migrate https://wiki.openfisca.fr non-obsolete content to [GitHub wiki](https://wiki.openfisca.fr) or documentation and remove [wiki service](https://wiki.openfisca.fr) from server?

**Comment by maukoquiroga** [comment]
Après passage rapide il me semble que tout est périmé, sauf peut-être :

- Contenu MesAides @guillett tu confirmes ?
- Contenu Tunisie @sandcha tu confirmes ?

Après confirmation, je propose de débrancher le wiki.
