### ISSUE TITLE
Contact remaining and newly discovered consumers of v21 API

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-ops#77]

**Comment by maukoquiroga** [comment]
@Morendil Could you tell me who they are ?

**Comment by MattiSG** [comment]
We don't know who the users of https://fr.openfisca.org/api/v21 are. There was never a commitment made to keep on supporting them, and this version is now over 30 months old. Unless one can come up with a list of these users, we will simply stop the server at some point when migrating to a new deployment process, and it will be up to them to adapt. Closing this issue now :wink:
