### ISSUE TITLE
Remove VPS

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-ops#85]
Nouveau schéma d’hébergement:

 Sur Netlify:
 - [x] fr.openfisca.org

 Sur Scalingo:
 - [x] legislation.fr.openfisca.org
 - [x] legislation.demo.openfisca.org

Sur Scalingo, avec dépôts décorrélés (cf discussion sur https://github.com/openfisca/openfisca-france/pull/1310):
 - [x] v21.api.fr.openfisca.org - https://github.com/openfisca/openfisca-france-api
 - [x] v24.api.fr.openfisca.org - https://github.com/openfisca/openfisca-france-api
 - [x] latest.api.fr.openfisca.org - https://github.com/openfisca/openfisca-france-api
 - [x] api.demo.openfisca.org - https://github.com/openfisca/openfisca-country-template-api

Temporairement:
 - [x] api.fr.openfisca.org = VPS
 - [x] fr.openfisca.org/api/* -> proxy vers api.fr.openfisca.org/api/*
 - [x] fr.openfisca.org/legislation/  -> proxy vers api.fr.openfisca.org/legislation/

Continuité de service:
 - [ ] fr.openfisca.org/legislation/ -> proxy vers legislation.fr.openfisca.org
 - [ ] demo.openfisca.org -> CNAME vers legislation.demo.openfisca.org
 - [ ] fr.openfisca.org/api/v21/ -> proxy vers v21.api.fr.openfisca.org
 - [ ] fr.openfisca.org/api/v24/ -> proxy vers v24.api.fr.openfisca.org
 - [ ] fr.openfisca.org/api/latest/ -> proxy vers api.fr.openfisca.org
 - [ ] www.openfisca.fr -> CNAME vers fr.openfisca.org
 - [ ] reproduire fr.openfisca.org/api/ (un simple JSON) dans Netlify

**Comment by sandcha** [comment]
Cf. openfisca/fr.openfisca.org#29
